source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "haml"
gem "sass"
gem "compass"
gem "thin"
gem "eventmachine"
gem "parallel"
gem "multi_json"
gem "oj"
gem 'imdb', "0.8.1"
